apiVersion: v1
kind: Pod
metadata:
  name: myapachepod
  labels:
    name: apache
    tier: frontend
spec:
  containers:
    - name: myapachepod
      image: richeb/apachetest:{{ .Values.image.tag }}
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: myapachepod-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    name: apache
    tier: frontend