apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.pod.name }}
  labels:
    name: apache
    tier: frontend
spec:
  containers:
    - name: myapachepod
      image: richeb/apachetest:{{ .Values.image.tag }}
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    name: apache
    tier: frontend

---
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ .Values.limitRange.name }}
spec:
  limits:
    - type: Container
      default:
        cpu: {{ .Values.limitRange.cpuDefault | default "100m" }}
      defaultRequest:
        cpu: {{ .Values.limitRange.cpuDefault | default "100m" }}
      max:
        cpu: {{ .Values.limitRange.cpuMax | default "500m" }}
      min:
        cpu: {{ .Values.limitRange.cpuMin | default "100m" }}





