apiVersion: v1
kind: Service
metadata:
  name: myapachepod-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    name: apache
    tier: frontend